name: Release Android APK

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android NDK
        run: sdkmanager "ndk;29.0.13846066"

      - name: Configure environment
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/29.0.13846066" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/29.0.13846066" >> $GITHUB_ENV

      - name: Grant execute permission
        run: |
          chmod +x gradlew
          chmod +x scripts/build-native-libs.sh
          chmod +x scripts/build-go-lib.sh

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Find APK
        id: find_apk
        shell: bash
        run: |
          APK=$(find app/build/outputs -type f -name "*.apk" | grep -v "unsigned" | head -n 1)

          if [ -z "$APK" ]; then
            echo "APK not found!"
            exit 1
          fi

          echo "APK найден:"
          echo "$APK"

          mkdir output

          cp "$APK" output/Hoplet-${{ github.event.release.tag_name }}.apk

          echo "apk_path=output/Hoplet-${{ github.event.release.tag_name }}.apk" >> $GITHUB_OUTPUT

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.find_apk.outputs.apk_path }}