name: Release Android APK

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"
          cache: gradle

      - uses: actions/setup-go@v5
        with:
          go-version: "1.25"
          cache: true

      - uses: android-actions/setup-android@v3

      - run: sdkmanager "ndk;29.0.13846066"

      - run: |
          echo "ANDROID_NDK_HOME=$ANDROID_SDK_ROOT/ndk/29.0.13846066" >> $GITHUB_ENV
          echo "ANDROID_NDK_ROOT=$ANDROID_SDK_ROOT/ndk/29.0.13846066" >> $GITHUB_ENV

      - name: Restore keystore
        run: |
          mkdir -p app

          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > app/release.keystore

          cat > local.properties <<EOF
          KEYSTORE_FILE=release.keystore
          KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          EOF

          echo "Keystore:"
          ls -lh app/release.keystore

      - run: |
          chmod +x gradlew
          chmod +x scripts/build-go-lib.sh
          chmod +x scripts/build-native-libs.sh

      - run: ./gradlew assembleRelease

      - name: Collect APK
        run: |
          mkdir release-assets
          find app -type f -name "*.apk" -exec cp {} release-assets/ \;

      - uses: softprops/action-gh-release@v2
        with:
          files: release-assets/*